name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Codestral
    provider: mistral
    model: codestral-latest
    apiKey: GS50xXVvMmBEXzvOGJrmi2O6EGW7xLyE
  - name: Qwen2.5-Coder 3B
    provider: ollama
    model: qwen2.5-coder:3b
    roles:
      - chat
      - edit
      - apply
  - name: codestral:latest 
    provider: ollama
    model: codestral:latest 
    roles:
      - chat
      - edit
      - apply      
  - name: devstral:24b
    provider: ollama
    model: devstral:24b 
    roles:
      - chat
      - edit
      - apply        
contextProviders:
  - name: "open"
    params: {}   